# Generated by Django 6.0.1 on 2026-02-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='levels',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_hours',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
