# Generated by Django 6.0.1 on 2026-02-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_profile_bio_profile_levels_profile_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='levels',
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_level',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
