# Generated by Django 6.0.1 on 2026-02-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_profile_levels_alter_profile_study_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='levels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
