# Generated by Django 6.0.1 on 2026-02-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_studybuddyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studybuddyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
