# Generated by Django 6.0.1 on 2026-02-04 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_quizquestion_quizsubject_quizoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='website.quizsubject'),
        ),
    ]
