# Generated by Django 6.0.1 on 2026-02-04 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_quizattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='created_at',
            new_name='attempted_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='study_level',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.quizsubject'),
        ),
    ]
