# Generated by Django 6.0.1 on 2026-02-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_created_at_quizattempt_attempted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_level',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='QuizSubject',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
