# Generated by Django 6.0.1 on 2026-02-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_buddyrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuddyRequest',
        ),
    ]
